seed: 10
output_dir: /mnt/data4/made_workspace/newlm-output/test-2
tokenizer:
  # Every params for BertWordPieceTokenizer.train
  config:
    vocab_size: 30000
    min_frequency: 2
  input_dir: examples/data_small/
  max_len: 128
lm:
  model_type: "elmo-bert-causal"
  model:
    # Every params for transformers.BertConfig
    config:
      vocab_size: 30000
      hidden_size: 512
      num_attention_heads: 8
      num_hidden_layers: 6
      intermediate_size: 2048
      max_position_embeddings: 1024
      is_decoder: true # bert-causal
    create_params: # other params for LMBuilder.create
      # train_params: # params for Trainer.train inside LMBuilder.create
      #   resume_from_checkpoint: latest
  hf_trainer:
    # total-size per-batch.
    # i.e. num_GPU * accum_step * batch-size = total-size
    total_batch_size: 8
    # Every params for transformers.TrainingArguments
    args:
      per_device_train_batch_size: 1
      max_steps: 20
      save_steps: 40000
      prediction_loss_only: true
      # optimizer, according to the paper
      learning_rate: 0.0001
      warmup_steps: 10000
      weight_decay: 0.01
  train_path: examples/data_small/text.txt
glue:
  # tasks: ["cola", "mnli", "qnli"] # if not defined, would train all tasks
  hf_trainer:
    total_batch_size: 32
    args:
      evaluation_strategy: "epoch"
      save_strategy: "epoch"
      learning_rate: 0.00002
      per_device_train_batch_size: 4
      per_device_eval_batch_size: 4
      num_train_epochs: 3
      weight_decay: 0.01
wandb:
  run_basename: exp-gcloud
