seed: 386
output_dir: /mnt/data4/made_workspace/newlm-output/bert-causal-en.100-percent/checkpoint-1000000-output/seed386
tokenizer:
  pretrained: /mnt/data4/made_workspace/newlm-output/bert-causal-en.100-percent/checkpoint-1000000/
lm:
  model_type: "bert-causal"
  pretrained: /mnt/data4/made_workspace/newlm-output/bert-causal-en.100-percent/checkpoint-1000000/
glue:
  tasks: ["mrpc"] # if not defined, would train all tasks
  hf_trainer:
    total_batch_size: 32
    args:
      evaluation_strategy: "epoch"
      save_strategy: "epoch"
      learning_rate: 0.00002
      per_device_train_batch_size: 16
      per_device_eval_batch_size: 16
      num_train_epochs: 3
      weight_decay: 0.01
      save_total_limit: 1
wandb:
  run_basename: exp-gcloud-1M
