seed: 10
output_dir: outputs/en.100-percent.elmo-bert-causal-v4-finetune
# output_dir: outputs/en.100-percent.elmo-bert-causal-same_tokenizer-v4-finetune # same_tokenizer
tokenizer:
  pretrained: outputs/en.100-percent.bert-causal/model
lm:
  model_type: "elmo-bert-causal-l2r-r2l-v4"
  model:
    # Every params for transformers.BertConfig
    config:
      vocab_size: 30000
      hidden_size: 768
      num_attention_heads: 12
      num_hidden_layers: 12
      intermediate_size: 3072
      max_position_embeddings: 1024
      is_decoder: true # bert-causal
  pretrained_l2r: outputs/en.100-percent.bert-causal/model
  pretrained_r2l: outputs/en.100-percent.bert-causal-r2l/model
  # pretrained_r2l: outputs/en.100-percent.bert-causal-r2l-v2/model # same_tokenizer
glue:
  tasks: ["cola", "mrpc", "rte", "sst2", "stsb"]
  hf_trainer:
    total_batch_size: 32
    args:
      evaluation_strategy: "epoch"
      save_strategy: "epoch"
      learning_rate: 0.00002
      per_device_train_batch_size: 16
      per_device_eval_batch_size: 32
      num_train_epochs: 4
      weight_decay: 0.01
      save_total_limit: 1
  qqp:
    hf_trainer:
      args:
        per_device_train_batch_size: 8
  mnli:
    hf_trainer:
      args:
        per_device_train_batch_size: 8
  qnli:
    hf_trainer:
      args:
        per_device_train_batch_size: 4
wandb:
  run_basename: elmo-l2r-r2l-v4
