seed: 10
output_dir: /mnt/data4/made_workspace/newlm-output/tmp
tokenizer:
  pretrained: /mnt/data4/made_workspace/newlm-output/bert-causal-en.100-percent/checkpoint-1000000
  # pretrained_l2r: /mnt/data4/made_workspace/newlm-output/bert-causal-en.100-percent/checkpoint-1000000
  # pretrained_r2l: /mnt/data1/made_workspace/newlm-output/bert-causal-en.100-percent-r2l/checkpoint-1000000
lm:
  model_type: "bert-causal"
glue:
  tasks: ["cola", "mrpc", "rte", "stsb", "sst2", "qnli", "mnli", "qqp"]
  cola:
    pretrained: /mnt/data4/made_workspace/newlm-output/best_l2r_r2l_finetuned/best_l2r_pretrained_lr4e-4/cola/checkpoint-1605/
  #   pretrained_l2r: /mnt/data4/made_workspace/newlm-output/best_l2r_r2l_finetuned/best_l2r_pretrained_lr4e-4/cola/checkpoint-1605/
  #   pretrained_r2l: /mnt/data4/made_workspace/newlm-output/best_l2r_r2l_finetuned/best_r2l_pretrained_lr1e-4/cola/checkpoint-1605/
  mnli:
    pretrained: /mnt/data4/made_workspace/newlm-output/best_l2r_r2l_finetuned/best_l2r_pretrained_lr4e-4/mnli/checkpoint-24544/
  #   pretrained_l2r: /mnt/data4/made_workspace/newlm-output/best_l2r_r2l_finetuned/best_l2r_pretrained_lr4e-4/mnli/checkpoint-24544/
  #   pretrained_r2l: /mnt/data4/made_workspace/newlm-output/best_l2r_r2l_finetuned/best_r2l_pretrained_lr1e-4/mnli/checkpoint-49088/
  mrpc:
    pretrained: /mnt/data4/made_workspace/newlm-output/best_l2r_r2l_finetuned/best_l2r_pretrained_lr4e-4/mrpc/checkpoint-460/
  #   pretrained_l2r: /mnt/data4/made_workspace/newlm-output/best_l2r_r2l_finetuned/best_l2r_pretrained_lr4e-4/mrpc/checkpoint-460/
  #   pretrained_r2l: /mnt/data4/made_workspace/newlm-output/best_l2r_r2l_finetuned/best_r2l_pretrained_lr1e-4/mrpc/checkpoint-345/
  qnli:
    pretrained: /mnt/data4/made_workspace/newlm-output/best_l2r_r2l_finetuned/best_l2r_pretrained_lr4e-4/qnli/checkpoint-13092/
  #   pretrained_l2r: /mnt/data4/made_workspace/newlm-output/best_l2r_r2l_finetuned/best_l2r_pretrained_lr4e-4/qnli/checkpoint-13092/
  #   pretrained_r2l: /mnt/data4/made_workspace/newlm-output/best_l2r_r2l_finetuned/best_r2l_pretrained_lr1e-4/qnli/checkpoint-6546/
  qqp:
    pretrained: /mnt/data4/made_workspace/newlm-output/best_l2r_r2l_finetuned/best_l2r_pretrained_lr4e-4/qqp/checkpoint-45480/
  #   pretrained_l2r: /mnt/data4/made_workspace/newlm-output/best_l2r_r2l_finetuned/best_l2r_pretrained_lr4e-4/qqp/checkpoint-45480/
  #   pretrained_r2l: /mnt/data4/made_workspace/newlm-output/best_l2r_r2l_finetuned/best_r2l_pretrained_lr1e-4/qqp/checkpoint-34110/
  rte:
    pretrained: /mnt/data4/made_workspace/newlm-output/best_l2r_r2l_finetuned/best_l2r_pretrained_lr4e-4/rte/checkpoint-234/
  #   pretrained_l2r: /mnt/data4/made_workspace/newlm-output/best_l2r_r2l_finetuned/best_l2r_pretrained_lr4e-4/rte/checkpoint-234/
  #   pretrained_r2l: /mnt/data4/made_workspace/newlm-output/best_l2r_r2l_finetuned/best_r2l_pretrained_lr1e-4/rte/checkpoint-312/
  sst2:
    pretrained: /mnt/data4/made_workspace/newlm-output/best_l2r_r2l_finetuned/best_l2r_pretrained_lr4e-4/sst2/checkpoint-6315/
  #   pretrained_l2r: /mnt/data4/made_workspace/newlm-output/best_l2r_r2l_finetuned/best_l2r_pretrained_lr4e-4/sst2/checkpoint-6315/
  #   pretrained_r2l: /mnt/data4/made_workspace/newlm-output/best_l2r_r2l_finetuned/best_r2l_pretrained_lr1e-4/sst2/checkpoint-2105/
  stsb:
    pretrained: /mnt/data4/made_workspace/newlm-output/best_l2r_r2l_finetuned/best_l2r_pretrained_lr4e-4/stsb/checkpoint-720/
  #   pretrained_l2r: /mnt/data4/made_workspace/newlm-output/best_l2r_r2l_finetuned/best_l2r_pretrained_lr4e-4/stsb/checkpoint-720/
  #   pretrained_r2l: /mnt/data4/made_workspace/newlm-output/best_l2r_r2l_finetuned/best_r2l_pretrained_lr1e-4/stsb/checkpoint-1440/
wandb:
  run_basename: ens-1M

# python -m newlm run_glue_predict --config_file="examples/configs/run-predict-glue.yaml" --test_data="test"
