seed: 10
output_dir: /mnt/data4/made_workspace/newlm-output/best_l2r_r2l_finetuned/ens-l2r_4e-4-l2r_2e-4
tokenizer:
  pretrained:
  ensembles:
    bert-causal: /mnt/data4/made_workspace/newlm-output/bert-causal-en.100-percent/checkpoint-1000000
lm:
  model_type:
glue:
  tasks: ["cola", "mrpc", "rte", "stsb", "sst2", "qnli", "mnli", "qqp"]
  cola:
    ensembles:
      bert-causal:
        - /mnt/data4/made_workspace/newlm-output/best_l2r_r2l_finetuned/best_l2r_pretrained_lr4e-4/cola/checkpoint-1605/
        - /mnt/data4/made_workspace/newlm-output/best_l2r_r2l_finetuned/best_l2r_pretrained_lr2e-4/cola/checkpoint-801/
  mnli:
    ensembles:
      bert-causal:
        - /mnt/data4/made_workspace/newlm-output/best_l2r_r2l_finetuned/best_l2r_pretrained_lr4e-4/mnli/checkpoint-24544/
        - /mnt/data4/made_workspace/newlm-output/best_l2r_r2l_finetuned/best_l2r_pretrained_lr2e-4/mnli/checkpoint-98176/
  mrpc:
    ensembles:
      bert-causal:
        - /mnt/data4/made_workspace/newlm-output/best_l2r_r2l_finetuned/best_l2r_pretrained_lr4e-4/mrpc/checkpoint-460/
        - /mnt/data4/made_workspace/newlm-output/best_l2r_r2l_finetuned/best_l2r_pretrained_lr2e-4/mrpc/checkpoint-920/
  qnli:
    ensembles:
      bert-causal:
        - /mnt/data4/made_workspace/newlm-output/best_l2r_r2l_finetuned/best_l2r_pretrained_lr4e-4/qnli/checkpoint-13092/
        - /mnt/data4/made_workspace/newlm-output/best_l2r_r2l_finetuned/best_l2r_pretrained_lr2e-4/qnli/checkpoint-26184/
  qqp:
    ensembles:
      bert-causal:
        - /mnt/data4/made_workspace/newlm-output/best_l2r_r2l_finetuned/best_l2r_pretrained_lr4e-4/qqp/checkpoint-45480/
        - /mnt/data4/made_workspace/newlm-output/best_l2r_r2l_finetuned/best_l2r_pretrained_lr2e-4/qqp/checkpoint-90964/
  rte:
    ensembles:
      bert-causal:
        - /mnt/data4/made_workspace/newlm-output/best_l2r_r2l_finetuned/best_l2r_pretrained_lr4e-4/rte/checkpoint-234/
        - /mnt/data4/made_workspace/newlm-output/best_l2r_r2l_finetuned/best_l2r_pretrained_lr2e-4/rte/checkpoint-156/
  sst2:
    ensembles:
      bert-causal:
        - /mnt/data4/made_workspace/newlm-output/best_l2r_r2l_finetuned/best_l2r_pretrained_lr4e-4/sst2/checkpoint-6315/
        - /mnt/data4/made_workspace/newlm-output/best_l2r_r2l_finetuned/best_l2r_pretrained_lr2e-4/sst2/checkpoint-8420/
  stsb:
    ensembles:
      bert-causal:
        - /mnt/data4/made_workspace/newlm-output/best_l2r_r2l_finetuned/best_l2r_pretrained_lr4e-4/stsb/checkpoint-720/
        - /mnt/data4/made_workspace/newlm-output/best_l2r_r2l_finetuned/best_l2r_pretrained_lr2e-4/stsb/checkpoint-1440/
wandb:
  run_basename: exp-gcloud-ens-1M

# python -m newlm run_predict_ensemble_v2 --config_file="examples/configs/run-predict-ensemble-v2.yaml"
