seed: 10
output_dir: /mnt/data4/made_workspace/newlm-output/test-200k-l2r
tokenizer:
  pretrained: /mnt/data4/made_workspace/newlm-output/bert-causal-en.100-percent/checkpoint-1000000
  # pretrained_l2r: /mnt/data4/made_workspace/newlm-output/bert-causal-en.100-percent/checkpoint-1000000
  # pretrained_r2l: /mnt/data1/made_workspace/newlm-output/bert-causal-en.100-percent-r2l/checkpoint-1000000
lm:
  model_type: "bert-causal"
glue:
  tasks: ["cola", "mrpc", "rte", "stsb", "sst2", "qnli", "mnli", "qqp"]
  cola:
  pretrained: /mnt/data4/made_workspace/newlm-output/best_l2r_r2l_finetuned/200k-best_l2r_pretrained_lr4e-4/cola/checkpoint-1605/
  #   pretrained_r2l: /mnt/data4/made_workspace/newlm-output/best_l2r_r2l_finetuned/200k-best_r2l_pretrained_lr1e-4-l2rtokenizer/cola/checkpoint-2140/
  mnli:
  pretrained: /mnt/data4/made_workspace/newlm-output/best_l2r_r2l_finetuned/200k-best_l2r_pretrained_lr4e-4/mnli/checkpoint-98176/
  #   pretrained_r2l: /mnt/data4/made_workspace/newlm-output/best_l2r_r2l_finetuned/200k-best_r2l_pretrained_lr1e-4-l2rtokenizer/mnli/checkpoint-36816/
  mrpc:
  pretrained: /mnt/data4/made_workspace/newlm-output/best_l2r_r2l_finetuned/200k-best_l2r_pretrained_lr4e-4/mrpc/checkpoint-460/
  #   pretrained_r2l: /mnt/data4/made_workspace/newlm-output/best_l2r_r2l_finetuned/200k-best_r2l_pretrained_lr1e-4-l2rtokenizer/mrpc/checkpoint-460/
  qnli:
  pretrained: /mnt/data4/made_workspace/newlm-output/best_l2r_r2l_finetuned/200k-best_l2r_pretrained_lr4e-4/qnli/checkpoint-19638/
  #   pretrained_r2l: /mnt/data4/made_workspace/newlm-output/best_l2r_r2l_finetuned/200k-best_r2l_pretrained_lr1e-4-l2rtokenizer/qnli/checkpoint-13092/
  qqp:
  pretrained: /mnt/data4/made_workspace/newlm-output/best_l2r_r2l_finetuned/200k-best_l2r_pretrained_lr4e-4/qqp/checkpoint-45480/
  #   pretrained_r2l: /mnt/data4/made_workspace/newlm-output/best_l2r_r2l_finetuned/200k-best_r2l_pretrained_lr1e-4-l2rtokenizer/qqp/checkpoint-45480/
  rte:
  pretrained: /mnt/data4/made_workspace/newlm-output/best_l2r_r2l_finetuned/200k-best_l2r_pretrained_lr4e-4/rte/checkpoint-624/
  #   pretrained_r2l: /mnt/data4/made_workspace/newlm-output/best_l2r_r2l_finetuned/200k-best_r2l_pretrained_lr1e-4-l2rtokenizer/rte/checkpoint-234/
  sst2:
  pretrained: /mnt/data4/made_workspace/newlm-output/best_l2r_r2l_finetuned/200k-best_l2r_pretrained_lr4e-4/sst2/checkpoint-4210/
  #   pretrained_r2l: /mnt/data4/made_workspace/newlm-output/best_l2r_r2l_finetuned/200k-best_r2l_pretrained_lr1e-4-l2rtokenizer/sst2/checkpoint-2104/
  stsb:
  pretrained: /mnt/data4/made_workspace/newlm-output/best_l2r_r2l_finetuned/200k-best_l2r_pretrained_lr4e-4/stsb/checkpoint-1440/
  #   pretrained_r2l: /mnt/data4/made_workspace/newlm-output/best_l2r_r2l_finetuned/200k-best_r2l_pretrained_lr1e-4-l2rtokenizer/stsb/checkpoint-720/
wandb:
  run_basename: testpredict-200k

# python -m newlm run_glue_predict --config_file="examples/configs/run-predict-glue.yaml" --test_data="test"
