seed: 42
output_dir: outputs/trial1/
tokenizer:
  # Every params for BertWordPieceTokenizer.train
  config:
    vocab_size: 30000
    min_frequency: 2
  input_dir: examples/data/text/id_csui/
  # pretrained: "bert-base-uncased" # for glue and lm without tokenizer
  max_len: 128
lm:
  # pretrained: "bert-base-uncased" # for glue
  model:
    # Every params for transformers.BertConfig
    config:
      vocab_size: 30000
      hidden_size: 512
      num_attention_heads: 2
      num_hidden_layers: 4
      intermediate_size: 1024
    create_params: # other params for LMBuilder.create
      use_nsp: true
      # train_params: # params for Trainer.train inside LMBuilder.create
      #   resume_from_checkpoint: latest
      #   #   if resume_from_checkpoint: 'latest' would load from latest checkpoint in output_dir
      #   #   else would followed the official hf guideline
  hf_trainer:
    # total-size per-batch.
    # i.e. num_GPU * accum_step * batch-size = total-size
    total_batch_size: 256
    # Every params for transformers.TrainingArguments
    args:
      per_device_train_batch_size: 16
      max_steps: 9000
      save_steps: 500
      save_total_limit: 2
      prediction_loss_only: true
      learning_rate: 0.0001
      warmup_steps: 10000
      weight_decay: 0.01
  train_path: examples/data/text/id_csui/text.txt
glue:
  from_scratch: false
  # tasks: ["cola", "mnli", "qnli"] # if not defined, train all tasks
  hf_trainer:
    total_batch_size: 32
    args:
      evaluation_strategy: "epoch"
      save_strategy: "epoch"
      learning_rate: 0.00002
      per_device_train_batch_size: 16
      per_device_eval_batch_size: 16
      num_train_epochs: 2
      weight_decay: 0.01
  # cola: # custom training arguments for each task
  #   hf_trainer:
  #     args:
  #       learning_rate: 0.1
wandb:
  run_basename: exp1
