seed: 42
output_dir: outputs/trial1/
tokenizer:
  pretrained: "bert-base-uncased"
  max_len: 128
lm:
  pretrained: "bert-base-uncased"
glue:
  # tasks: ["cola", "mnli", "qnli"] # if not defined, train all tasks
  hf_trainer:
    args:
      evaluation_strategy: "epoch"
      save_strategy: "epoch"
      learning_rate: 0.00002
      per_device_train_batch_size: 16
      per_device_eval_batch_size: 16
      num_train_epochs: 2
      weight_decay: 0.01
  # cola: # custom training arguments for each task
  #   hf_trainer:
  #     args:
  #       learning_rate: 0.1
wandb:
  run_basename: exp1
