seed: 42
output_dir: outputs/trial1/en.1-percent.mlm
tokenizer:
  pretrained: "outputs/en.1-percent.mlm/model"
  max_len: 512
lm:
  pretrained: "outputs/en.1-percent.mlm/model"
glue:
  tasks: ["rte"]
  hf_trainer:
    args:
      evaluation_strategy: "epoch"
      save_strategy: "epoch"
      learning_rate: 0.00002
      per_device_train_batch_size: 16
      per_device_eval_batch_size: 16
      num_train_epochs: 3
      weight_decay: 0.01
  # cola:
  #   hf_trainer:
  #     args:
  #       learning_rate: 0.1
wandb:
  run_basename: exp1

