seed: 42
output_dir: outputs/en.1-percent.elmo.ctx1024
tokenizer:
  pretrained: "outputs/en.1-percent.elmo.ctx1024/model"
  max_len: 1024
lm:
  model_type: "elmo-gpt"
  pretrained: "outputs/en.1-percent.elmo.ctx1024/model"
  model: # model config if you run from scratch
      config:
              n_positions: 1024
              n_ctx: 1024
glue:
  tasks: ["sst2"]
  hf_trainer:
    args:
      evaluation_strategy: "epoch"
      save_strategy: "epoch"
      learning_rate: 0.00002
      per_device_train_batch_size: 4
      gradient_accumulation_steps: 4
      per_device_eval_batch_size: 16
      num_train_epochs: 3
      weight_decay: 0.01
  # cola:
  #   hf_trainer:
  #     args:
  #       learning_rate: 0.1
wandb:
  run_basename: exp1

