seed: 42
output_dir: outputs/en.1-percent-bert-causal/
tokenizer:
  pretrained: "outputs/en.1-percent-bert-causal/model"
  max_len: 512
lm:
  model_type: "bert-causal"
  pretrained: "outputs/en.1-percent-bert-causal/model"
glue:
  tasks: ["qqp", "sst2", "rte", "stsb", "wnli", "qnli"]
  hf_trainer:
    args:
      evaluation_strategy: "epoch"
      save_strategy: "epoch"
      learning_rate: 0.00002
      per_device_train_batch_size: 8
      gradient_accumulation_steps: 2
      per_device_eval_batch_size: 16
      num_train_epochs: 3
      weight_decay: 0.01
  # cola:
  #   hf_trainer:
  #     args:
  #       learning_rate: 0.1
wandb:
  run_basename: causal-bert

