seed: 42
output_dir: outputs/trial1/
tokenizer:
  pretrained: outputs/trial1/model
  max_len: 128
lm:
  model:
    config:
      vocab_size: 30000
      hidden_size: 512
      num_attention_heads: 2
      num_hidden_layers: 4
      intermediate_size: 1024
  hf_trainer:
    total_batch_size: 16
    args:
      per_device_train_batch_size: 16
      num_train_epochs: 1
      save_steps: 500
      save_total_limit: 2
      prediction_loss_only: true
  train_path: examples/data/text/id_csui/text.txt
wandb:
  run_basename: exp1
